import Foundation

/// Complete exercise database for XomFit
/// Organized by muscle group with form tips
struct ExerciseDatabase {
    static let all: [Exercise] = chest + back + shoulders + legs + arms + core
    
    // MARK: - Chest
    static let chest: [Exercise] = [
        Exercise(id: "ex-bench-flat", name: "Bench Press", muscleGroups: [.chest, .triceps, .shoulders], equipment: .barbell, category: .compound,
                 description: "Flat barbell bench press — the king of chest exercises.",
                 tips: ["Retract shoulder blades", "Feet flat on floor", "Touch bar to mid-chest", "Drive through your feet"]),
        Exercise(id: "ex-bench-incline", name: "Incline Bench Press", muscleGroups: [.chest, .shoulders, .triceps], equipment: .barbell, category: .compound,
                 description: "Incline barbell press targeting upper chest.",
                 tips: ["Set bench to 30-45 degrees", "Lower bar to upper chest", "Don't flare elbows too wide"]),
        Exercise(id: "ex-bench-db", name: "Dumbbell Bench Press", muscleGroups: [.chest, .triceps, .shoulders], equipment: .dumbbell, category: .compound,
                 description: "Dumbbell variation for better range of motion.",
                 tips: ["Full range of motion at the bottom", "Press dumbbells together at top", "Control the negative"]),
        Exercise(id: "ex-incline-db", name: "Incline Dumbbell Press", muscleGroups: [.chest, .shoulders, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Incline dumbbell press for upper chest development.",
                 tips: ["30-45 degree incline", "Don't bounce at the bottom", "Squeeze at the top"]),
        Exercise(id: "ex-chest-fly", name: "Cable Chest Fly", muscleGroups: [.chest], equipment: .cable, category: .isolation,
                 description: "Cable flyes for chest isolation and stretch.",
                 tips: ["Slight bend in elbows throughout", "Squeeze chest at the center", "Control the stretch"]),
        Exercise(id: "ex-dips", name: "Dips", muscleGroups: [.chest, .triceps, .shoulders], equipment: .bodyweight, category: .compound,
                 description: "Parallel bar dips — lean forward to target chest.",
                 tips: ["Lean forward for chest emphasis", "Go to at least 90 degrees", "Don't swing"]),
        Exercise(id: "ex-pushup", name: "Push-ups", muscleGroups: [.chest, .triceps, .shoulders], equipment: .bodyweight, category: .compound,
                 description: "Classic bodyweight push-up.",
                 tips: ["Keep core tight", "Full range of motion", "Hands slightly wider than shoulders"]),
        Exercise(id: "ex-machine-press", name: "Machine Chest Press", muscleGroups: [.chest, .triceps], equipment: .machine, category: .compound,
                 description: "Machine press for controlled chest work.",
                 tips: ["Adjust seat height so handles align with mid-chest", "Don't lock out elbows", "Squeeze at full extension"]),
        Exercise(id: "ex-decline-bench", name: "Decline Bench Press", muscleGroups: [.chest, .triceps], equipment: .barbell, category: .compound,
                 description: "Decline barbell press targeting lower chest fibers.",
                 tips: ["Set bench to 15-30 degree decline", "Lower bar to lower chest", "Keep feet locked in pads"]),
        Exercise(id: "ex-decline-db-press", name: "Decline Dumbbell Press", muscleGroups: [.chest, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Decline dumbbell press for lower chest emphasis with greater range of motion.",
                 tips: ["Control the dumbbells on the way down", "Press up and slightly inward", "Don't go too steep on the decline"]),
        Exercise(id: "ex-incline-machine-press", name: "Incline Machine Press", muscleGroups: [.chest, .shoulders], equipment: .machine, category: .compound,
                 description: "Machine incline press for upper chest with guided path.",
                 tips: ["Adjust seat so handles align with upper chest", "Drive through the full range of motion", "Don't lock out elbows"]),
        Exercise(id: "ex-cable-high-fly", name: "Cable High-to-Low Fly", muscleGroups: [.chest], equipment: .cable, category: .isolation,
                 description: "High cable fly sweeping downward to target the lower chest.",
                 tips: ["Set pulleys to high position", "Slight forward lean", "Squeeze at the bottom of the movement"]),
        Exercise(id: "ex-cable-low-fly", name: "Cable Low-to-High Fly", muscleGroups: [.chest], equipment: .cable, category: .isolation,
                 description: "Low cable fly sweeping upward to target the upper chest.",
                 tips: ["Set pulleys to low position", "Bring hands together at upper chest height", "Control the stretch on the way back"]),
        Exercise(id: "ex-landmine-press", name: "Landmine Press", muscleGroups: [.chest, .shoulders], equipment: .barbell, category: .compound,
                 description: "Angled barbell press using a landmine attachment for chest and shoulder work.",
                 tips: ["Press at an angle, not straight up", "Use close grip for more chest activation", "Brace your core throughout"]),
        Exercise(id: "ex-pec-deck", name: "Pec Deck / Machine Fly", muscleGroups: [.chest], equipment: .machine, category: .isolation,
                 description: "Machine fly for controlled chest isolation.",
                 tips: ["Adjust seat so handles are at chest height", "Don't let the weight stack slam", "Squeeze at the center", "Slight bend in elbows"]),
        Exercise(id: "ex-db-fly", name: "Dumbbell Fly", muscleGroups: [.chest], equipment: .dumbbell, category: .isolation,
                 description: "Flat bench dumbbell fly for chest stretch and isolation.",
                 tips: ["Slight bend in elbows throughout", "Lower until you feel a deep stretch", "Squeeze chest at the top"]),
        Exercise(id: "ex-svend-press", name: "Svend Press", muscleGroups: [.chest], equipment: .dumbbell, category: .isolation,
                 description: "Press a plate or dumbbell out from your chest while squeezing inward for inner chest activation.",
                 tips: ["Squeeze the weight between your palms the entire time", "Press straight out from mid-chest", "Use light weight and focus on the contraction"]),
    ]
    
    // MARK: - Back
    static let back: [Exercise] = [
        Exercise(id: "ex-deadlift", name: "Deadlift", muscleGroups: [.back, .hamstrings, .glutes, .traps], equipment: .barbell, category: .compound,
                 description: "Conventional deadlift — the ultimate posterior chain builder.",
                 tips: ["Bar over mid-foot", "Neutral spine", "Push the floor away", "Lock out at the top"]),
        Exercise(id: "ex-row-barbell", name: "Barbell Row", muscleGroups: [.back, .lats, .biceps], equipment: .barbell, category: .compound,
                 description: "Bent-over barbell row for back thickness.",
                 tips: ["Hinge at hips to ~45 degrees", "Pull to lower chest/upper abs", "Squeeze shoulder blades together"]),
        Exercise(id: "ex-row-db", name: "Dumbbell Row", muscleGroups: [.back, .lats, .biceps], equipment: .dumbbell, category: .compound,
                 description: "Single-arm dumbbell row.",
                 tips: ["Keep back flat", "Pull elbow past torso", "Don't rotate your body"]),
        Exercise(id: "ex-pullup", name: "Pull-ups", muscleGroups: [.lats, .back, .biceps], equipment: .bodyweight, category: .compound,
                 description: "Overhand grip pull-up — king of lat exercises.",
                 tips: ["Full dead hang at bottom", "Pull chest to bar", "Control the negative"]),
        Exercise(id: "ex-chinup", name: "Chin-ups", muscleGroups: [.lats, .biceps, .back], equipment: .bodyweight, category: .compound,
                 description: "Underhand grip for more bicep involvement.",
                 tips: ["Supinated grip shoulder width", "Drive elbows down", "Full range of motion"]),
        Exercise(id: "ex-lat-pulldown", name: "Lat Pulldown", muscleGroups: [.lats, .back, .biceps], equipment: .cable, category: .compound,
                 description: "Cable pulldown for lat width.",
                 tips: ["Lean back slightly", "Pull to upper chest", "Don't use momentum"]),
        Exercise(id: "ex-cable-row", name: "Seated Cable Row", muscleGroups: [.back, .lats, .biceps], equipment: .cable, category: .compound,
                 description: "Seated cable row for mid-back thickness.",
                 tips: ["Keep chest up", "Pull to stomach", "Squeeze at full contraction"]),
        Exercise(id: "ex-face-pull", name: "Face Pulls", muscleGroups: [.shoulders, .traps, .back], equipment: .cable, category: .isolation,
                 description: "Cable face pulls for rear delts and posture.",
                 tips: ["Pull rope to face level", "Externally rotate at the end", "Light weight, high reps"]),
        Exercise(id: "ex-chest-supported-row", name: "Chest Supported Row", muscleGroups: [.back, .lats], equipment: .dumbbell, category: .compound,
                 description: "Dumbbell row with chest on an incline bench, eliminating momentum.",
                 tips: ["Set bench to about 30-45 degrees", "Let arms hang fully at the bottom", "Pull elbows back and squeeze shoulder blades"]),
        Exercise(id: "ex-tbar-row", name: "T-Bar Row", muscleGroups: [.back, .lats, .biceps], equipment: .barbell, category: .compound,
                 description: "T-bar row for mid-back thickness.",
                 tips: ["Keep chest against pad if available", "Pull to upper abs", "Don't round your lower back"]),
        Exercise(id: "ex-pendlay-row", name: "Pendlay Row", muscleGroups: [.back, .lats], equipment: .barbell, category: .compound,
                 description: "Strict barbell row from the floor each rep for explosive back power.",
                 tips: ["Bar returns to floor between each rep", "Back parallel to floor", "Explosive pull, controlled return"]),
        Exercise(id: "ex-close-grip-pulldown", name: "Close Grip Lat Pulldown", muscleGroups: [.lats, .biceps], equipment: .cable, category: .compound,
                 description: "Lat pulldown with a close/neutral grip for lat emphasis.",
                 tips: ["Use a V-bar or close grip handle", "Pull to upper chest", "Lean back slightly and squeeze lats"]),
        Exercise(id: "ex-reverse-grip-pulldown", name: "Reverse Grip Lat Pulldown", muscleGroups: [.lats, .biceps], equipment: .cable, category: .compound,
                 description: "Underhand grip pulldown for lower lat and bicep engagement.",
                 tips: ["Supinated grip shoulder width", "Pull to upper chest", "Focus on driving elbows down and back"]),
        Exercise(id: "ex-straight-arm-pulldown", name: "Straight Arm Pulldown", muscleGroups: [.lats], equipment: .cable, category: .isolation,
                 description: "Cable pulldown with straight arms for lat isolation.",
                 tips: ["Keep arms nearly straight throughout", "Pull the bar to your thighs", "Squeeze lats at the bottom"]),
        Exercise(id: "ex-cable-reverse-fly", name: "Cable Reverse Fly", muscleGroups: [.back, .shoulders], equipment: .cable, category: .isolation,
                 description: "Cable fly in reverse to target rear delts and upper back.",
                 tips: ["Cross cables at face height", "Lead with elbows", "Control the weight back to start"]),
        Exercise(id: "ex-machine-row", name: "Machine Row", muscleGroups: [.back, .lats], equipment: .machine, category: .compound,
                 description: "Plate-loaded or selectorized row machine for back development.",
                 tips: ["Adjust chest pad so arms fully extend", "Pull to stomach", "Squeeze shoulder blades at peak contraction"]),
        Exercise(id: "ex-pullover-machine", name: "Pullover Machine", muscleGroups: [.lats, .back], equipment: .machine, category: .isolation,
                 description: "Machine pullover for lat stretch and contraction.",
                 tips: ["Full stretch overhead", "Pull with lats, not arms", "Slow and controlled throughout"]),
        Exercise(id: "ex-seal-row", name: "Seal Row", muscleGroups: [.back, .lats], equipment: .dumbbell, category: .compound,
                 description: "Chest-supported row on a flat elevated bench, eliminating all momentum.",
                 tips: ["Lie face down on elevated bench", "Let dumbbells hang with full stretch", "Pull elbows back and squeeze"]),
    ]
    
    // MARK: - Shoulders
    static let shoulders: [Exercise] = [
        Exercise(id: "ex-ohp", name: "Overhead Press", muscleGroups: [.shoulders, .triceps], equipment: .barbell, category: .compound,
                 description: "Standing barbell overhead press.",
                 tips: ["Brace your core", "Press bar slightly back", "Full lockout overhead", "Don't lean back excessively"]),
        Exercise(id: "ex-db-shoulder-press", name: "Dumbbell Shoulder Press", muscleGroups: [.shoulders, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Seated or standing dumbbell press.",
                 tips: ["Don't go too heavy", "Full range of motion", "Press up and slightly inward"]),
        Exercise(id: "ex-lateral-raise", name: "Lateral Raises", muscleGroups: [.shoulders], equipment: .dumbbell, category: .isolation,
                 description: "Dumbbell lateral raises for side delt width.",
                 tips: ["Slight bend in elbows", "Raise to shoulder height", "Lead with your elbows, not hands", "Control the negative"]),
        Exercise(id: "ex-front-raise", name: "Front Raises", muscleGroups: [.shoulders], equipment: .dumbbell, category: .isolation,
                 description: "Front delt isolation.",
                 tips: ["Alternating or together", "Don't swing", "Raise to eye level"]),
        Exercise(id: "ex-rear-delt-fly", name: "Rear Delt Fly", muscleGroups: [.shoulders, .back], equipment: .dumbbell, category: .isolation,
                 description: "Bent-over rear delt flyes.",
                 tips: ["Bend over to near parallel", "Lead with elbows", "Squeeze at the top"]),
        Exercise(id: "ex-shrugs", name: "Barbell Shrugs", muscleGroups: [.traps], equipment: .barbell, category: .isolation,
                 description: "Barbell shrugs for trap development.",
                 tips: ["Straight up and down", "Hold at the top", "Don't roll your shoulders"]),
        Exercise(id: "ex-machine-shoulder-press", name: "Machine Shoulder Press", muscleGroups: [.shoulders, .triceps], equipment: .machine, category: .compound,
                 description: "Seated machine press for controlled overhead work.",
                 tips: ["Adjust seat so handles start at shoulder height", "Press to full extension without locking out", "Keep back against pad"]),
        Exercise(id: "ex-cable-lateral-raise", name: "Cable Lateral Raise", muscleGroups: [.shoulders], equipment: .cable, category: .isolation,
                 description: "Single-arm lateral raise using a cable for constant tension.",
                 tips: ["Stand sideways to the cable", "Raise to shoulder height", "Control the negative for maximum tension"]),
        Exercise(id: "ex-machine-lateral-raise", name: "Machine Lateral Raise", muscleGroups: [.shoulders], equipment: .machine, category: .isolation,
                 description: "Machine lateral raise for consistent side delt isolation.",
                 tips: ["Adjust pads to sit just above elbows", "Raise to shoulder height", "Don't shrug up"]),
        Exercise(id: "ex-cable-front-raise", name: "Cable Front Raise", muscleGroups: [.shoulders], equipment: .cable, category: .isolation,
                 description: "Front raise using a cable for constant tension on the front delts.",
                 tips: ["Face away from the cable", "Raise to eye level", "Don't use momentum"]),
        Exercise(id: "ex-db-shrugs", name: "Dumbbell Shrugs", muscleGroups: [.traps], equipment: .dumbbell, category: .isolation,
                 description: "Dumbbell shrugs for trap development with greater range of motion.",
                 tips: ["Straight up and down", "Hold at the top for a count", "Don't roll your shoulders"]),
        Exercise(id: "ex-machine-shrugs", name: "Machine Shrugs", muscleGroups: [.traps], equipment: .machine, category: .isolation,
                 description: "Machine shrugs for heavy, controlled trap work.",
                 tips: ["Stand centered in the machine", "Shrug straight up", "Pause at the top"]),
        Exercise(id: "ex-arnold-press", name: "Arnold Press", muscleGroups: [.shoulders, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Rotating dumbbell press that hits all three delt heads.",
                 tips: ["Start with palms facing you", "Rotate palms outward as you press up", "Full lockout overhead"]),
        Exercise(id: "ex-upright-row", name: "Upright Row", muscleGroups: [.shoulders, .traps], equipment: .barbell, category: .compound,
                 description: "Barbell upright row for shoulders and traps.",
                 tips: ["Use a wider grip to reduce shoulder impingement risk", "Pull to chin height", "Lead with elbows"]),
        Exercise(id: "ex-cable-rear-delt-fly", name: "Cable Rear Delt Fly", muscleGroups: [.shoulders], equipment: .cable, category: .isolation,
                 description: "Cable fly targeting the rear deltoids.",
                 tips: ["Set cables at shoulder height", "Pull outward and back", "Squeeze rear delts at peak contraction"]),
        Exercise(id: "ex-reverse-pec-deck", name: "Reverse Pec Deck", muscleGroups: [.shoulders], equipment: .machine, category: .isolation,
                 description: "Reverse pec deck machine for rear delt isolation.",
                 tips: ["Face the pad with chest against it", "Lead with elbows", "Squeeze at the back", "Don't use momentum"]),
    ]
    
    // MARK: - Legs
    static let legs: [Exercise] = [
        Exercise(id: "ex-squat", name: "Squat", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .barbell, category: .compound,
                 description: "Back squat — the king of leg exercises.",
                 tips: ["Bar on upper traps", "Feet shoulder width", "Break at hips and knees together", "Thighs to parallel or below"]),
        Exercise(id: "ex-front-squat", name: "Front Squat", muscleGroups: [.quads, .glutes], equipment: .barbell, category: .compound,
                 description: "Front squat for quad-dominant leg work.",
                 tips: ["Elbows high", "Stay upright", "Go as deep as mobility allows"]),
        Exercise(id: "ex-leg-press", name: "Leg Press", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .machine, category: .compound,
                 description: "Machine leg press for heavy leg work.",
                 tips: ["Don't lock out knees", "Full range of motion", "Feet shoulder width on platform"]),
        Exercise(id: "ex-rdl", name: "Romanian Deadlift", muscleGroups: [.hamstrings, .glutes, .back], equipment: .barbell, category: .compound,
                 description: "RDL for hamstring and glute development.",
                 tips: ["Slight knee bend", "Push hips back", "Bar stays close to legs", "Feel the hamstring stretch"]),
        Exercise(id: "ex-lunge", name: "Walking Lunges", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .dumbbell, category: .compound,
                 description: "Walking lunges with dumbbells.",
                 tips: ["Long stride", "Back knee almost touches ground", "Keep torso upright"]),
        Exercise(id: "ex-leg-curl", name: "Leg Curl", muscleGroups: [.hamstrings], equipment: .machine, category: .isolation,
                 description: "Machine leg curl for hamstring isolation.",
                 tips: ["Control the negative", "Full range of motion", "Don't lift hips off pad"]),
        Exercise(id: "ex-leg-ext", name: "Leg Extension", muscleGroups: [.quads], equipment: .machine, category: .isolation,
                 description: "Machine leg extension for quad isolation.",
                 tips: ["Pause at full extension", "Control the descent", "Don't use momentum"]),
        Exercise(id: "ex-calf-raise", name: "Calf Raises", muscleGroups: [.calves], equipment: .machine, category: .isolation,
                 description: "Standing calf raises.",
                 tips: ["Full stretch at bottom", "Pause at top", "Slow and controlled"]),
        Exercise(id: "ex-hip-thrust", name: "Hip Thrust", muscleGroups: [.glutes, .hamstrings], equipment: .barbell, category: .compound,
                 description: "Barbell hip thrust for glute max activation.",
                 tips: ["Back on bench, bar on hips", "Drive through heels", "Squeeze glutes at top", "Chin tucked"]),
        Exercise(id: "ex-hack-squat", name: "Hack Squat", muscleGroups: [.quads, .glutes], equipment: .machine, category: .compound,
                 description: "Machine hack squat for quad-focused leg development.",
                 tips: ["Feet shoulder width on platform", "Go to at least parallel", "Don't lock out knees at the top"]),
        Exercise(id: "ex-goblet-squat", name: "Goblet Squat", muscleGroups: [.quads, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Squat holding a dumbbell at chest height for front-loaded quad work.",
                 tips: ["Hold dumbbell vertically at chest", "Elbows inside knees at the bottom", "Keep torso upright"]),
        Exercise(id: "ex-bulgarian-split-squat", name: "Bulgarian Split Squat", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .dumbbell, category: .compound,
                 description: "Single-leg squat with rear foot elevated on a bench.",
                 tips: ["Rear foot on bench behind you", "Drop back knee straight down", "Keep front shin fairly vertical", "Don't lean forward excessively"]),
        Exercise(id: "ex-sumo-deadlift", name: "Sumo Deadlift", muscleGroups: [.hamstrings, .glutes, .back], equipment: .barbell, category: .compound,
                 description: "Wide stance deadlift emphasizing hips and inner thighs.",
                 tips: ["Wide stance, toes pointed out", "Grip inside the knees", "Push the floor apart", "Keep chest up"]),
        Exercise(id: "ex-db-rdl", name: "Dumbbell RDL", muscleGroups: [.hamstrings, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Romanian deadlift with dumbbells for hamstring and glute work.",
                 tips: ["Slight knee bend", "Push hips back", "Dumbbells stay close to legs", "Feel the hamstring stretch"]),
        Exercise(id: "ex-seated-leg-curl", name: "Seated Leg Curl", muscleGroups: [.hamstrings], equipment: .machine, category: .isolation,
                 description: "Seated machine leg curl for hamstring isolation.",
                 tips: ["Adjust pad to sit just above your ankles", "Full range of motion", "Squeeze at full contraction"]),
        Exercise(id: "ex-glute-kickback", name: "Glute Kickback Machine", muscleGroups: [.glutes], equipment: .machine, category: .isolation,
                 description: "Machine kickback for targeted glute isolation.",
                 tips: ["Drive through your heel", "Squeeze glute at the top", "Don't hyperextend your lower back"]),
        Exercise(id: "ex-seated-calf-raise", name: "Seated Calf Raise", muscleGroups: [.calves], equipment: .machine, category: .isolation,
                 description: "Seated calf raise targeting the soleus muscle.",
                 tips: ["Full stretch at the bottom", "Pause at the top", "Slow and controlled reps"]),
        Exercise(id: "ex-smith-squat", name: "Smith Machine Squat", muscleGroups: [.quads, .glutes], equipment: .machine, category: .compound,
                 description: "Squat using the Smith machine for a guided bar path.",
                 tips: ["Feet slightly forward of the bar", "Go to parallel or below", "Don't rely entirely on the machine for balance"]),
        Exercise(id: "ex-step-ups", name: "Step-ups", muscleGroups: [.quads, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Step onto a bench or box holding dumbbells.",
                 tips: ["Drive through the heel of the top foot", "Don't push off the back foot", "Keep torso upright"]),
    ]
    
    // MARK: - Arms
    static let arms: [Exercise] = [
        Exercise(id: "ex-barbell-curl", name: "Barbell Curl", muscleGroups: [.biceps], equipment: .barbell, category: .isolation,
                 description: "Standing barbell curl.",
                 tips: ["Keep elbows pinned to sides", "Don't swing", "Full range of motion"]),
        Exercise(id: "ex-db-curl", name: "Dumbbell Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Standing or seated dumbbell curls.",
                 tips: ["Supinate at the top", "Control the negative", "Alternate or together"]),
        Exercise(id: "ex-hammer-curl", name: "Hammer Curl", muscleGroups: [.biceps, .forearms], equipment: .dumbbell, category: .isolation,
                 description: "Neutral grip curls for brachialis and forearms.",
                 tips: ["Neutral grip throughout", "Don't swing", "Great for forearm development"]),
        Exercise(id: "ex-preacher-curl", name: "Preacher Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Preacher bench curls for strict bicep isolation.",
                 tips: ["Full stretch at bottom", "Don't come all the way up", "Strict form"]),
        Exercise(id: "ex-tricep-pushdown", name: "Tricep Pushdown", muscleGroups: [.triceps], equipment: .cable, category: .isolation,
                 description: "Cable pushdowns with rope or bar.",
                 tips: ["Elbows pinned to sides", "Full extension", "Squeeze at the bottom"]),
        Exercise(id: "ex-skull-crusher", name: "Skull Crushers", muscleGroups: [.triceps], equipment: .barbell, category: .isolation,
                 description: "Lying tricep extension with EZ bar.",
                 tips: ["Lower to forehead or behind head", "Keep elbows in", "Control the weight"]),
        Exercise(id: "ex-overhead-ext", name: "Overhead Tricep Extension", muscleGroups: [.triceps], equipment: .dumbbell, category: .isolation,
                 description: "Overhead single or double dumbbell tricep extension.",
                 tips: ["Keep elbows close to head", "Full stretch at bottom", "Lock out at top"]),
        Exercise(id: "ex-close-grip-bench", name: "Close Grip Bench Press", muscleGroups: [.triceps, .chest], equipment: .barbell, category: .compound,
                 description: "Narrow grip bench press for tricep emphasis.",
                 tips: ["Hands shoulder-width or slightly narrower", "Elbows tucked", "Touch lower chest"]),
        Exercise(id: "ex-cable-curl", name: "Cable Curl", muscleGroups: [.biceps], equipment: .cable, category: .isolation,
                 description: "Standing cable curl for constant tension on the biceps.",
                 tips: ["Keep elbows pinned to sides", "Use a straight bar or EZ bar attachment", "Squeeze at the top"]),
        Exercise(id: "ex-concentration-curl", name: "Concentration Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Seated single-arm curl with elbow braced against inner thigh.",
                 tips: ["Brace elbow against inner thigh", "Curl all the way up and squeeze", "Control the negative"]),
        Exercise(id: "ex-ez-bar-curl", name: "EZ Bar Curl", muscleGroups: [.biceps], equipment: .barbell, category: .isolation,
                 description: "Curl with an EZ bar for a more wrist-friendly grip angle.",
                 tips: ["Use the angled grip to reduce wrist strain", "Keep elbows pinned", "Full range of motion"]),
        Exercise(id: "ex-spider-curl", name: "Spider Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Curl performed face down on an incline bench for strict bicep isolation.",
                 tips: ["Chest against incline bench", "Arms hang straight down", "No swinging — strict form only"]),
        Exercise(id: "ex-incline-db-curl", name: "Incline Dumbbell Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Seated incline curl for a deep bicep stretch at the bottom.",
                 tips: ["Set bench to 45-60 degrees", "Let arms hang fully for a stretch", "Curl without moving upper arms"]),
        Exercise(id: "ex-cable-overhead-tri-ext", name: "Cable Overhead Tricep Extension", muscleGroups: [.triceps], equipment: .cable, category: .isolation,
                 description: "Overhead cable extension for a deep tricep stretch and contraction.",
                 tips: ["Face away from the cable machine", "Keep elbows close to your head", "Extend fully and squeeze"]),
        Exercise(id: "ex-tricep-dip-machine", name: "Tricep Dip Machine", muscleGroups: [.triceps], equipment: .machine, category: .isolation,
                 description: "Machine-assisted dip focusing on tricep activation.",
                 tips: ["Keep torso upright for tricep emphasis", "Full range of motion", "Don't let the weight stack slam"]),
        Exercise(id: "ex-kickbacks", name: "Kickbacks", muscleGroups: [.triceps], equipment: .dumbbell, category: .isolation,
                 description: "Dumbbell kickback for tricep isolation.",
                 tips: ["Hinge forward and pin upper arm to your side", "Extend fully behind you", "Squeeze at full extension"]),
        Exercise(id: "ex-reverse-curl", name: "Reverse Curl", muscleGroups: [.forearms, .biceps], equipment: .barbell, category: .isolation,
                 description: "Overhand grip curl targeting the brachioradialis and forearms.",
                 tips: ["Overhand (pronated) grip", "Keep elbows pinned", "Use lighter weight than standard curls"]),
        Exercise(id: "ex-wrist-curl", name: "Wrist Curl", muscleGroups: [.forearms], equipment: .dumbbell, category: .isolation,
                 description: "Seated wrist curl for forearm flexor development.",
                 tips: ["Rest forearms on thighs or a bench", "Full range of motion at the wrist", "Control the weight — don't rush"]),
    ]
    
    // MARK: - Core
    static let core: [Exercise] = [
        Exercise(id: "ex-plank", name: "Plank", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Isometric core hold.",
                 tips: ["Straight line from head to heels", "Don't let hips sag", "Breathe normally"]),
        Exercise(id: "ex-hanging-leg-raise", name: "Hanging Leg Raise", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Hanging from a bar, raise legs to parallel or above.",
                 tips: ["Control the swing", "Curl pelvis up", "Slow negative"]),
        Exercise(id: "ex-cable-crunch", name: "Cable Crunch", muscleGroups: [.abs], equipment: .cable, category: .isolation,
                 description: "Kneeling cable crunch for weighted ab work.",
                 tips: ["Crunch down, don't pull with arms", "Round your spine", "Squeeze at the bottom"]),
        Exercise(id: "ex-ab-wheel", name: "Ab Wheel Rollout", muscleGroups: [.abs], equipment: .other, category: .isolation,
                 description: "Ab wheel rollout for deep core activation.",
                 tips: ["Start from knees", "Don't collapse at the bottom", "Brace core throughout"]),
        Exercise(id: "ex-cable-woodchop", name: "Cable Woodchop", muscleGroups: [.abs], equipment: .cable, category: .isolation,
                 description: "Rotational cable movement for obliques and core.",
                 tips: ["Rotate through your torso, not your arms", "Keep arms extended", "Control the return"]),
        Exercise(id: "ex-russian-twist", name: "Russian Twist", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Seated twist for oblique and core engagement.",
                 tips: ["Lean back slightly with feet off the ground", "Rotate through your torso", "Touch the ground on each side"]),
        Exercise(id: "ex-decline-situp", name: "Decline Sit-up", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Sit-up on a decline bench for increased ab resistance.",
                 tips: ["Hook feet under the pads", "Cross arms over chest or behind head", "Control the negative"]),
        Exercise(id: "ex-dead-bug", name: "Dead Bug", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Supine core stability exercise extending opposite arm and leg.",
                 tips: ["Keep lower back pressed into the floor", "Extend opposite arm and leg slowly", "Exhale as you extend"]),
        Exercise(id: "ex-pallof-press", name: "Pallof Press", muscleGroups: [.abs], equipment: .cable, category: .isolation,
                 description: "Anti-rotation cable press for deep core stability.",
                 tips: ["Stand sideways to the cable", "Press straight out from your chest", "Resist the rotation — that's the work"]),
        Exercise(id: "ex-mountain-climbers", name: "Mountain Climbers", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Dynamic plank variation driving knees to chest for core and cardio.",
                 tips: ["Keep hips level — don't bounce them up", "Drive knees toward chest quickly", "Keep core braced throughout"]),
    ]
    
    // MARK: - Search
    static func search(_ query: String) -> [Exercise] {
        if query.isEmpty { return all }
        let lowered = query.lowercased()
        return all.filter {
            $0.name.lowercased().contains(lowered) ||
            $0.muscleGroups.contains(where: { $0.rawValue.contains(lowered) }) ||
            $0.equipment.rawValue.contains(lowered)
        }
    }
    
    static func byMuscleGroup(_ group: MuscleGroup) -> [Exercise] {
        all.filter { $0.muscleGroups.contains(group) }
    }
    
    static func byEquipment(_ equipment: Equipment) -> [Exercise] {
        all.filter { $0.equipment == equipment }
    }
}
