import Foundation

/// Complete exercise database for XomFit
/// Organized by muscle group with form tips
struct ExerciseDatabase {
    static let all: [Exercise] = chest + back + shoulders + legs + arms + core + unilateral + machineAndCableExtras + bodyweightExtras + mobility

    /// O(1) lookup by exercise id. Replaces `all.first(where: { $0.id == ... })` callsites
    /// which were O(n) per lookup and frequently used inside view-rendered loops (#321).
    static let byId: [String: Exercise] = Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })

    /// O(1) lookup by exercise name. Replaces `all.first(where: { $0.name == ... })` callsites,
    /// notably in feed muscle-group filters that ran for every visible feed item (#321).
    static let byName: [String: Exercise] = Dictionary(uniqueKeysWithValues: all.map { ($0.name, $0) })
    
    // MARK: - Chest
    static let chest: [Exercise] = [
        Exercise(id: "ex-bench-flat", name: "Bench Press", muscleGroups: [.chest, .triceps, .shoulders], equipment: .barbell, category: .compound,
                 description: "Flat barbell bench press — the king of chest exercises.",
                 tips: ["Retract shoulder blades", "Feet flat on floor", "Touch bar to mid-chest", "Drive through your feet"]),
        Exercise(id: "ex-bench-incline", name: "Incline Bench Press", muscleGroups: [.chest, .shoulders, .triceps], equipment: .barbell, category: .compound,
                 description: "Incline barbell press targeting upper chest.",
                 tips: ["Set bench to 30-45 degrees", "Lower bar to upper chest", "Don't flare elbows too wide"]),
        Exercise(id: "ex-bench-db", name: "Dumbbell Bench Press", muscleGroups: [.chest, .triceps, .shoulders], equipment: .dumbbell, category: .compound,
                 description: "Dumbbell variation for better range of motion.",
                 tips: ["Full range of motion at the bottom", "Press dumbbells together at top", "Control the negative"],
                 supportsUnilateral: true),
        Exercise(id: "ex-incline-db", name: "Incline Dumbbell Press", muscleGroups: [.chest, .shoulders, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Incline dumbbell press for upper chest development.",
                 tips: ["30-45 degree incline", "Don't bounce at the bottom", "Squeeze at the top"],
                 supportsUnilateral: true),
        Exercise(id: "ex-chest-fly", name: "Cable Chest Fly", muscleGroups: [.chest], equipment: .cable, category: .isolation,
                 description: "Cable flyes for chest isolation and stretch.",
                 tips: ["Slight bend in elbows throughout", "Squeeze chest at the center", "Control the stretch"]),
        Exercise(id: "ex-dips", name: "Dips", muscleGroups: [.chest, .triceps, .shoulders], equipment: .bodyweight, category: .compound,
                 description: "Parallel bar dips — lean forward to target chest.",
                 tips: ["Lean forward for chest emphasis", "Go to at least 90 degrees", "Don't swing"]),
        Exercise(id: "ex-pushup", name: "Push-ups", muscleGroups: [.chest, .triceps, .shoulders], equipment: .bodyweight, category: .compound,
                 description: "Classic bodyweight push-up.",
                 tips: ["Keep core tight", "Full range of motion", "Hands slightly wider than shoulders"]),
        Exercise(id: "ex-machine-press", name: "Machine Chest Press", muscleGroups: [.chest, .triceps], equipment: .machine, category: .compound,
                 description: "Machine press for controlled chest work.",
                 tips: ["Adjust seat height so handles align with mid-chest", "Don't lock out elbows", "Squeeze at full extension"]),
        Exercise(id: "ex-decline-bench", name: "Decline Bench Press", muscleGroups: [.chest, .triceps], equipment: .barbell, category: .compound,
                 description: "Decline barbell press targeting lower chest fibers.",
                 tips: ["Set bench to 15-30 degree decline", "Lower bar to lower chest", "Keep feet locked in pads"]),
        Exercise(id: "ex-decline-db-press", name: "Decline Dumbbell Press", muscleGroups: [.chest, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Decline dumbbell press for lower chest emphasis with greater range of motion.",
                 tips: ["Control the dumbbells on the way down", "Press up and slightly inward", "Don't go too steep on the decline"]),
        Exercise(id: "ex-incline-machine-press", name: "Incline Machine Press", muscleGroups: [.chest, .shoulders], equipment: .machine, category: .compound,
                 description: "Machine incline press for upper chest with guided path.",
                 tips: ["Adjust seat so handles align with upper chest", "Drive through the full range of motion", "Don't lock out elbows"]),
        Exercise(id: "ex-cable-high-fly", name: "Cable High-to-Low Fly", muscleGroups: [.chest], equipment: .cable, category: .isolation,
                 description: "High cable fly sweeping downward to target the lower chest.",
                 tips: ["Set pulleys to high position", "Slight forward lean", "Squeeze at the bottom of the movement"],
                 supportedAttachments: [.dHandle]),
        Exercise(id: "ex-cable-low-fly", name: "Cable Low-to-High Fly", muscleGroups: [.chest], equipment: .cable, category: .isolation,
                 description: "Low cable fly sweeping upward to target the upper chest.",
                 tips: ["Set pulleys to low position", "Bring hands together at upper chest height", "Control the stretch on the way back"],
                 supportedAttachments: [.dHandle]),
        Exercise(id: "ex-landmine-press", name: "Landmine Press", muscleGroups: [.chest, .shoulders], equipment: .barbell, category: .compound,
                 description: "Angled barbell press using a landmine attachment for chest and shoulder work.",
                 tips: ["Press at an angle, not straight up", "Use close grip for more chest activation", "Brace your core throughout"]),
        Exercise(id: "ex-pec-deck", name: "Pec Deck / Machine Fly", muscleGroups: [.chest], equipment: .machine, category: .isolation,
                 description: "Machine fly for controlled chest isolation.",
                 tips: ["Adjust seat so handles are at chest height", "Don't let the weight stack slam", "Squeeze at the center", "Slight bend in elbows"]),
        Exercise(id: "ex-db-fly", name: "Dumbbell Fly", muscleGroups: [.chest], equipment: .dumbbell, category: .isolation,
                 description: "Flat bench dumbbell fly for chest stretch and isolation.",
                 tips: ["Slight bend in elbows throughout", "Lower until you feel a deep stretch", "Squeeze chest at the top"]),
        Exercise(id: "ex-svend-press", name: "Svend Press", muscleGroups: [.chest], equipment: .dumbbell, category: .isolation,
                 description: "Press a plate or dumbbell out from your chest while squeezing inward for inner chest activation.",
                 tips: ["Squeeze the weight between your palms the entire time", "Press straight out from mid-chest", "Use light weight and focus on the contraction"]),
    ]
    
    // MARK: - Back
    static let back: [Exercise] = [
        Exercise(id: "ex-deadlift", name: "Deadlift", muscleGroups: [.back, .hamstrings, .glutes, .traps], equipment: .barbell, category: .compound,
                 description: "Conventional deadlift — the ultimate posterior chain builder.",
                 tips: ["Bar over mid-foot", "Neutral spine", "Push the floor away", "Lock out at the top"]),
        Exercise(id: "ex-row-barbell", name: "Barbell Row", muscleGroups: [.back, .lats, .biceps], equipment: .barbell, category: .compound,
                 description: "Bent-over barbell row for back thickness.",
                 tips: ["Hinge at hips to ~45 degrees", "Pull to lower chest/upper abs", "Squeeze shoulder blades together"],
                 supportedGrips: [.overhand, .underhand]),
        Exercise(id: "ex-row-db", name: "Dumbbell Row", muscleGroups: [.back, .lats, .biceps], equipment: .dumbbell, category: .compound,
                 description: "Single-arm dumbbell row.",
                 tips: ["Keep back flat", "Pull elbow past torso", "Don't rotate your body"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-pullup", name: "Pull-ups", muscleGroups: [.lats, .back, .biceps], equipment: .bodyweight, category: .compound,
                 description: "Overhand grip pull-up — king of lat exercises.",
                 tips: ["Full dead hang at bottom", "Pull chest to bar", "Control the negative"],
                 supportedGrips: [.overhand, .wide, .close]),
        Exercise(id: "ex-chinup", name: "Chin-ups", muscleGroups: [.lats, .biceps, .back], equipment: .bodyweight, category: .compound,
                 description: "Underhand grip for more bicep involvement.",
                 tips: ["Supinated grip shoulder width", "Drive elbows down", "Full range of motion"],
                 supportedGrips: [.underhand, .neutral]),
        Exercise(id: "ex-lat-pulldown", name: "Lat Pulldown", muscleGroups: [.lats, .back, .biceps], equipment: .cable, category: .compound,
                 description: "Cable pulldown for lat width.",
                 tips: ["Lean back slightly", "Pull to upper chest", "Don't use momentum"],
                 supportedGrips: [.overhand, .underhand, .neutral, .wide, .close],
                 supportedAttachments: [.rope, .straightBar, .vBar, .wideBar],
                 supportsUnilateral: true),
        Exercise(id: "ex-cable-row", name: "Seated Cable Row", muscleGroups: [.back, .lats, .biceps], equipment: .cable, category: .compound,
                 description: "Seated cable row for mid-back thickness.",
                 tips: ["Keep chest up", "Pull to stomach", "Squeeze at full contraction"],
                 supportedAttachments: [.rope, .straightBar, .vBar, .dHandle],
                 supportsUnilateral: true),
        Exercise(id: "ex-face-pull", name: "Face Pulls", muscleGroups: [.shoulders, .traps, .back], equipment: .cable, category: .isolation,
                 description: "Cable face pulls for rear delts and posture.",
                 tips: ["Pull rope to face level", "Externally rotate at the end", "Light weight, high reps"],
                 supportedAttachments: [.rope]),
        Exercise(id: "ex-chest-supported-row", name: "Chest Supported Row", muscleGroups: [.back, .lats], equipment: .dumbbell, category: .compound,
                 description: "Dumbbell row with chest on an incline bench, eliminating momentum.",
                 tips: ["Set bench to about 30-45 degrees", "Let arms hang fully at the bottom", "Pull elbows back and squeeze shoulder blades"]),
        Exercise(id: "ex-tbar-row", name: "T-Bar Row", muscleGroups: [.back, .lats, .biceps], equipment: .barbell, category: .compound,
                 description: "T-bar row for mid-back thickness.",
                 tips: ["Keep chest against pad if available", "Pull to upper abs", "Don't round your lower back"]),
        Exercise(id: "ex-pendlay-row", name: "Pendlay Row", muscleGroups: [.back, .lats], equipment: .barbell, category: .compound,
                 description: "Strict barbell row from the floor each rep for explosive back power.",
                 tips: ["Bar returns to floor between each rep", "Back parallel to floor", "Explosive pull, controlled return"]),
        Exercise(id: "ex-close-grip-pulldown", name: "Close Grip Lat Pulldown", muscleGroups: [.lats, .biceps], equipment: .cable, category: .compound,
                 description: "Lat pulldown with a close/neutral grip for lat emphasis.",
                 tips: ["Use a V-bar or close grip handle", "Pull to upper chest", "Lean back slightly and squeeze lats"],
                 supportedGrips: [.close, .neutral]),
        Exercise(id: "ex-reverse-grip-pulldown", name: "Reverse Grip Lat Pulldown", muscleGroups: [.lats, .biceps], equipment: .cable, category: .compound,
                 description: "Underhand grip pulldown for lower lat and bicep engagement.",
                 tips: ["Supinated grip shoulder width", "Pull to upper chest", "Focus on driving elbows down and back"]),
        Exercise(id: "ex-straight-arm-pulldown", name: "Straight Arm Pulldown", muscleGroups: [.lats], equipment: .cable, category: .isolation,
                 description: "Cable pulldown with straight arms for lat isolation.",
                 tips: ["Keep arms nearly straight throughout", "Pull the bar to your thighs", "Squeeze lats at the bottom"],
                 supportedAttachments: [.rope, .straightBar]),
        Exercise(id: "ex-cable-reverse-fly", name: "Cable Reverse Fly", muscleGroups: [.back, .shoulders], equipment: .cable, category: .isolation,
                 description: "Cable fly in reverse to target rear delts and upper back.",
                 tips: ["Cross cables at face height", "Lead with elbows", "Control the weight back to start"]),
        Exercise(id: "ex-machine-row", name: "Machine Row", muscleGroups: [.back, .lats], equipment: .machine, category: .compound,
                 description: "Plate-loaded or selectorized row machine for back development.",
                 tips: ["Adjust chest pad so arms fully extend", "Pull to stomach", "Squeeze shoulder blades at peak contraction"]),
        Exercise(id: "ex-pullover-machine", name: "Pullover Machine", muscleGroups: [.lats, .back], equipment: .machine, category: .isolation,
                 description: "Machine pullover for lat stretch and contraction.",
                 tips: ["Full stretch overhead", "Pull with lats, not arms", "Slow and controlled throughout"]),
        Exercise(id: "ex-seal-row", name: "Seal Row", muscleGroups: [.back, .lats], equipment: .dumbbell, category: .compound,
                 description: "Chest-supported row on a flat elevated bench, eliminating all momentum.",
                 tips: ["Lie face down on elevated bench", "Let dumbbells hang with full stretch", "Pull elbows back and squeeze"]),
    ]
    
    // MARK: - Shoulders
    static let shoulders: [Exercise] = [
        Exercise(id: "ex-ohp", name: "Overhead Press", muscleGroups: [.shoulders, .triceps], equipment: .barbell, category: .compound,
                 description: "Standing barbell overhead press.",
                 tips: ["Brace your core", "Press bar slightly back", "Full lockout overhead", "Don't lean back excessively"],
                 supportedPositions: [.seated, .standing]),
        Exercise(id: "ex-db-shoulder-press", name: "Dumbbell Shoulder Press", muscleGroups: [.shoulders, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Seated or standing dumbbell press.",
                 tips: ["Don't go too heavy", "Full range of motion", "Press up and slightly inward"],
                 supportedPositions: [.seated, .standing],
                 supportsUnilateral: true),
        Exercise(id: "ex-lateral-raise", name: "Lateral Raises", muscleGroups: [.shoulders], equipment: .dumbbell, category: .isolation,
                 description: "Dumbbell lateral raises for side delt width.",
                 tips: ["Slight bend in elbows", "Raise to shoulder height", "Lead with your elbows, not hands", "Control the negative"],
                 supportsUnilateral: true),
        Exercise(id: "ex-front-raise", name: "Front Raises", muscleGroups: [.shoulders], equipment: .dumbbell, category: .isolation,
                 description: "Front delt isolation.",
                 tips: ["Alternating or together", "Don't swing", "Raise to eye level"],
                 supportsUnilateral: true),
        Exercise(id: "ex-rear-delt-fly", name: "Rear Delt Fly", muscleGroups: [.shoulders, .back], equipment: .dumbbell, category: .isolation,
                 description: "Bent-over rear delt flyes.",
                 tips: ["Bend over to near parallel", "Lead with elbows", "Squeeze at the top"],
                 supportsUnilateral: true),
        Exercise(id: "ex-shrugs", name: "Barbell Shrugs", muscleGroups: [.traps], equipment: .barbell, category: .isolation,
                 description: "Barbell shrugs for trap development.",
                 tips: ["Straight up and down", "Hold at the top", "Don't roll your shoulders"]),
        Exercise(id: "ex-machine-shoulder-press", name: "Machine Shoulder Press", muscleGroups: [.shoulders, .triceps], equipment: .machine, category: .compound,
                 description: "Seated machine press for controlled overhead work.",
                 tips: ["Adjust seat so handles start at shoulder height", "Press to full extension without locking out", "Keep back against pad"]),
        Exercise(id: "ex-cable-lateral-raise", name: "Cable Lateral Raise", muscleGroups: [.shoulders], equipment: .cable, category: .isolation,
                 description: "Single-arm lateral raise using a cable for constant tension.",
                 tips: ["Stand sideways to the cable", "Raise to shoulder height", "Control the negative for maximum tension"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-machine-lateral-raise", name: "Machine Lateral Raise", muscleGroups: [.shoulders], equipment: .machine, category: .isolation,
                 description: "Machine lateral raise for consistent side delt isolation.",
                 tips: ["Adjust pads to sit just above elbows", "Raise to shoulder height", "Don't shrug up"]),
        Exercise(id: "ex-cable-front-raise", name: "Cable Front Raise", muscleGroups: [.shoulders], equipment: .cable, category: .isolation,
                 description: "Front raise using a cable for constant tension on the front delts.",
                 tips: ["Face away from the cable", "Raise to eye level", "Don't use momentum"]),
        Exercise(id: "ex-db-shrugs", name: "Dumbbell Shrugs", muscleGroups: [.traps], equipment: .dumbbell, category: .isolation,
                 description: "Dumbbell shrugs for trap development with greater range of motion.",
                 tips: ["Straight up and down", "Hold at the top for a count", "Don't roll your shoulders"],
                 supportsUnilateral: true),
        Exercise(id: "ex-machine-shrugs", name: "Machine Shrugs", muscleGroups: [.traps], equipment: .machine, category: .isolation,
                 description: "Machine shrugs for heavy, controlled trap work.",
                 tips: ["Stand centered in the machine", "Shrug straight up", "Pause at the top"]),
        Exercise(id: "ex-arnold-press", name: "Arnold Press", muscleGroups: [.shoulders, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Rotating dumbbell press that hits all three delt heads.",
                 tips: ["Start with palms facing you", "Rotate palms outward as you press up", "Full lockout overhead"]),
        Exercise(id: "ex-upright-row", name: "Upright Row", muscleGroups: [.shoulders, .traps], equipment: .barbell, category: .compound,
                 description: "Barbell upright row for shoulders and traps.",
                 tips: ["Use a wider grip to reduce shoulder impingement risk", "Pull to chin height", "Lead with elbows"]),
        Exercise(id: "ex-cable-rear-delt-fly", name: "Cable Rear Delt Fly", muscleGroups: [.shoulders], equipment: .cable, category: .isolation,
                 description: "Cable fly targeting the rear deltoids.",
                 tips: ["Set cables at shoulder height", "Pull outward and back", "Squeeze rear delts at peak contraction"]),
        Exercise(id: "ex-reverse-pec-deck", name: "Reverse Pec Deck", muscleGroups: [.shoulders], equipment: .machine, category: .isolation,
                 description: "Reverse pec deck machine for rear delt isolation.",
                 tips: ["Face the pad with chest against it", "Lead with elbows", "Squeeze at the back", "Don't use momentum"]),
    ]
    
    // MARK: - Legs
    static let legs: [Exercise] = [
        Exercise(id: "ex-squat", name: "Squat", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .barbell, category: .compound,
                 description: "Back squat — the king of leg exercises.",
                 tips: ["Bar on upper traps", "Feet shoulder width", "Break at hips and knees together", "Thighs to parallel or below"]),
        Exercise(id: "ex-front-squat", name: "Front Squat", muscleGroups: [.quads, .glutes], equipment: .barbell, category: .compound,
                 description: "Front squat for quad-dominant leg work.",
                 tips: ["Elbows high", "Stay upright", "Go as deep as mobility allows"]),
        Exercise(id: "ex-leg-press", name: "Leg Press", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .machine, category: .compound,
                 description: "Machine leg press for heavy leg work.",
                 tips: ["Don't lock out knees", "Full range of motion", "Feet shoulder width on platform"],
                 supportsUnilateral: true),
        Exercise(id: "ex-rdl", name: "Romanian Deadlift", muscleGroups: [.hamstrings, .glutes, .back], equipment: .barbell, category: .compound,
                 description: "RDL for hamstring and glute development.",
                 tips: ["Slight knee bend", "Push hips back", "Bar stays close to legs", "Feel the hamstring stretch"]),
        Exercise(id: "ex-lunge", name: "Walking Lunges", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .dumbbell, category: .compound,
                 description: "Walking lunges with dumbbells.",
                 tips: ["Long stride", "Back knee almost touches ground", "Keep torso upright"]),
        Exercise(id: "ex-leg-curl", name: "Leg Curl", muscleGroups: [.hamstrings], equipment: .machine, category: .isolation,
                 description: "Machine leg curl for hamstring isolation.",
                 tips: ["Control the negative", "Full range of motion", "Don't lift hips off pad"],
                 supportedPositions: [.seated, .lying],
                 supportsUnilateral: true),
        Exercise(id: "ex-leg-ext", name: "Leg Extension", muscleGroups: [.quads], equipment: .machine, category: .isolation,
                 description: "Machine leg extension for quad isolation.",
                 tips: ["Pause at full extension", "Control the descent", "Don't use momentum"],
                 supportsUnilateral: true),
        Exercise(id: "ex-calf-raise", name: "Calf Raises", muscleGroups: [.calves], equipment: .machine, category: .isolation,
                 description: "Standing calf raises.",
                 tips: ["Full stretch at bottom", "Pause at top", "Slow and controlled"],
                 supportsUnilateral: true),
        Exercise(id: "ex-hip-thrust", name: "Hip Thrust", muscleGroups: [.glutes, .hamstrings], equipment: .barbell, category: .compound,
                 description: "Barbell hip thrust for glute max activation.",
                 tips: ["Back on bench, bar on hips", "Drive through heels", "Squeeze glutes at top", "Chin tucked"],
                 supportsUnilateral: true),
        Exercise(id: "ex-hack-squat", name: "Hack Squat", muscleGroups: [.quads, .glutes], equipment: .machine, category: .compound,
                 description: "Machine hack squat for quad-focused leg development.",
                 tips: ["Feet shoulder width on platform", "Go to at least parallel", "Don't lock out knees at the top"]),
        Exercise(id: "ex-goblet-squat", name: "Goblet Squat", muscleGroups: [.quads, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Squat holding a dumbbell at chest height for front-loaded quad work.",
                 tips: ["Hold dumbbell vertically at chest", "Elbows inside knees at the bottom", "Keep torso upright"]),
        Exercise(id: "ex-bulgarian-split-squat", name: "Bulgarian Split Squat", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .dumbbell, category: .compound,
                 description: "Single-leg squat with rear foot elevated on a bench.",
                 tips: ["Rear foot on bench behind you", "Drop back knee straight down", "Keep front shin fairly vertical", "Don't lean forward excessively"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-sumo-deadlift", name: "Sumo Deadlift", muscleGroups: [.hamstrings, .glutes, .back], equipment: .barbell, category: .compound,
                 description: "Wide stance deadlift emphasizing hips and inner thighs.",
                 tips: ["Wide stance, toes pointed out", "Grip inside the knees", "Push the floor apart", "Keep chest up"]),
        Exercise(id: "ex-db-rdl", name: "Dumbbell RDL", muscleGroups: [.hamstrings, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Romanian deadlift with dumbbells for hamstring and glute work.",
                 tips: ["Slight knee bend", "Push hips back", "Dumbbells stay close to legs", "Feel the hamstring stretch"],
                 supportsUnilateral: true),
        Exercise(id: "ex-seated-leg-curl", name: "Seated Leg Curl", muscleGroups: [.hamstrings], equipment: .machine, category: .isolation,
                 description: "Seated machine leg curl for hamstring isolation.",
                 tips: ["Adjust pad to sit just above your ankles", "Full range of motion", "Squeeze at full contraction"]),
        Exercise(id: "ex-glute-kickback", name: "Glute Kickback Machine", muscleGroups: [.glutes], equipment: .machine, category: .isolation,
                 description: "Machine kickback for targeted glute isolation.",
                 tips: ["Drive through your heel", "Squeeze glute at the top", "Don't hyperextend your lower back"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-seated-calf-raise", name: "Seated Calf Raise", muscleGroups: [.calves], equipment: .machine, category: .isolation,
                 description: "Seated calf raise targeting the soleus muscle.",
                 tips: ["Full stretch at the bottom", "Pause at the top", "Slow and controlled reps"],
                 supportsUnilateral: true),
        Exercise(id: "ex-smith-squat", name: "Smith Machine Squat", muscleGroups: [.quads, .glutes], equipment: .machine, category: .compound,
                 description: "Squat using the Smith machine for a guided bar path.",
                 tips: ["Feet slightly forward of the bar", "Go to parallel or below", "Don't rely entirely on the machine for balance"]),
        Exercise(id: "ex-step-ups", name: "Step-ups", muscleGroups: [.quads, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Step onto a bench or box holding dumbbells.",
                 tips: ["Drive through the heel of the top foot", "Don't push off the back foot", "Keep torso upright"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
    ]
    
    // MARK: - Arms
    static let arms: [Exercise] = [
        Exercise(id: "ex-barbell-curl", name: "Barbell Curl", muscleGroups: [.biceps], equipment: .barbell, category: .isolation,
                 description: "Standing barbell curl.",
                 tips: ["Keep elbows pinned to sides", "Don't swing", "Full range of motion"],
                 supportedGrips: [.underhand, .overhand, .wide, .close]),
        Exercise(id: "ex-db-curl", name: "Dumbbell Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Standing or seated dumbbell curls.",
                 tips: ["Supinate at the top", "Control the negative", "Alternate or together"],
                 supportedPositions: [.seated, .standing, .incline],
                 supportsUnilateral: true),
        Exercise(id: "ex-hammer-curl", name: "Hammer Curl", muscleGroups: [.biceps, .forearms], equipment: .dumbbell, category: .isolation,
                 description: "Neutral grip curls for brachialis and forearms.",
                 tips: ["Neutral grip throughout", "Don't swing", "Great for forearm development"],
                 supportsUnilateral: true),
        Exercise(id: "ex-preacher-curl", name: "Preacher Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Preacher bench curls for strict bicep isolation.",
                 tips: ["Full stretch at bottom", "Don't come all the way up", "Strict form"],
                 supportsUnilateral: true),
        Exercise(id: "ex-tricep-pushdown", name: "Tricep Pushdown", muscleGroups: [.triceps], equipment: .cable, category: .isolation,
                 description: "Cable pushdowns with rope or bar.",
                 tips: ["Elbows pinned to sides", "Full extension", "Squeeze at the bottom"],
                 supportedAttachments: [.rope, .straightBar, .vBar],
                 supportsUnilateral: true),
        Exercise(id: "ex-skull-crusher", name: "Skull Crushers", muscleGroups: [.triceps], equipment: .barbell, category: .isolation,
                 description: "Lying tricep extension with EZ bar.",
                 tips: ["Lower to forehead or behind head", "Keep elbows in", "Control the weight"]),
        Exercise(id: "ex-overhead-ext", name: "Overhead Tricep Extension", muscleGroups: [.triceps], equipment: .dumbbell, category: .isolation,
                 description: "Overhead single or double dumbbell tricep extension.",
                 tips: ["Keep elbows close to head", "Full stretch at bottom", "Lock out at top"],
                 supportsUnilateral: true),
        Exercise(id: "ex-close-grip-bench", name: "Close Grip Bench Press", muscleGroups: [.triceps, .chest], equipment: .barbell, category: .compound,
                 description: "Narrow grip bench press for tricep emphasis.",
                 tips: ["Hands shoulder-width or slightly narrower", "Elbows tucked", "Touch lower chest"]),
        Exercise(id: "ex-cable-curl", name: "Cable Curl", muscleGroups: [.biceps], equipment: .cable, category: .isolation,
                 description: "Standing cable curl for constant tension on the biceps.",
                 tips: ["Keep elbows pinned to sides", "Use a straight bar or EZ bar attachment", "Squeeze at the top"],
                 supportedAttachments: [.rope, .straightBar, .ezBar],
                 supportsUnilateral: true),
        Exercise(id: "ex-concentration-curl", name: "Concentration Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Seated single-arm curl with elbow braced against inner thigh.",
                 tips: ["Brace elbow against inner thigh", "Curl all the way up and squeeze", "Control the negative"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-ez-bar-curl", name: "EZ Bar Curl", muscleGroups: [.biceps], equipment: .barbell, category: .isolation,
                 description: "Curl with an EZ bar for a more wrist-friendly grip angle.",
                 tips: ["Use the angled grip to reduce wrist strain", "Keep elbows pinned", "Full range of motion"]),
        Exercise(id: "ex-spider-curl", name: "Spider Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Curl performed face down on an incline bench for strict bicep isolation.",
                 tips: ["Chest against incline bench", "Arms hang straight down", "No swinging — strict form only"]),
        Exercise(id: "ex-incline-db-curl", name: "Incline Dumbbell Curl", muscleGroups: [.biceps], equipment: .dumbbell, category: .isolation,
                 description: "Seated incline curl for a deep bicep stretch at the bottom.",
                 tips: ["Set bench to 45-60 degrees", "Let arms hang fully for a stretch", "Curl without moving upper arms"],
                 supportsUnilateral: true),
        Exercise(id: "ex-cable-overhead-tri-ext", name: "Cable Overhead Tricep Extension", muscleGroups: [.triceps], equipment: .cable, category: .isolation,
                 description: "Overhead cable extension for a deep tricep stretch and contraction.",
                 tips: ["Face away from the cable machine", "Keep elbows close to your head", "Extend fully and squeeze"],
                 supportedAttachments: [.rope]),
        Exercise(id: "ex-tricep-dip-machine", name: "Tricep Dip Machine", muscleGroups: [.triceps], equipment: .machine, category: .isolation,
                 description: "Machine-assisted dip focusing on tricep activation.",
                 tips: ["Keep torso upright for tricep emphasis", "Full range of motion", "Don't let the weight stack slam"]),
        Exercise(id: "ex-kickbacks", name: "Kickbacks", muscleGroups: [.triceps], equipment: .dumbbell, category: .isolation,
                 description: "Dumbbell kickback for tricep isolation.",
                 tips: ["Hinge forward and pin upper arm to your side", "Extend fully behind you", "Squeeze at full extension"],
                 supportsUnilateral: true),
        Exercise(id: "ex-reverse-curl", name: "Reverse Curl", muscleGroups: [.forearms, .biceps], equipment: .barbell, category: .isolation,
                 description: "Overhand grip curl targeting the brachioradialis and forearms.",
                 tips: ["Overhand (pronated) grip", "Keep elbows pinned", "Use lighter weight than standard curls"]),
        Exercise(id: "ex-wrist-curl", name: "Wrist Curl", muscleGroups: [.forearms], equipment: .dumbbell, category: .isolation,
                 description: "Seated wrist curl for forearm flexor development.",
                 tips: ["Rest forearms on thighs or a bench", "Full range of motion at the wrist", "Control the weight — don't rush"],
                 supportsUnilateral: true),
    ]
    
    // MARK: - Core
    static let core: [Exercise] = [
        Exercise(id: "ex-plank", name: "Plank", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Isometric core hold.",
                 tips: ["Straight line from head to heels", "Don't let hips sag", "Breathe normally"]),
        Exercise(id: "ex-hanging-leg-raise", name: "Hanging Leg Raise", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Hanging from a bar, raise legs to parallel or above.",
                 tips: ["Control the swing", "Curl pelvis up", "Slow negative"]),
        Exercise(id: "ex-cable-crunch", name: "Cable Crunch", muscleGroups: [.abs], equipment: .cable, category: .isolation,
                 description: "Kneeling cable crunch for weighted ab work.",
                 tips: ["Crunch down, don't pull with arms", "Round your spine", "Squeeze at the bottom"],
                 supportsUnilateral: true),
        Exercise(id: "ex-ab-wheel", name: "Ab Wheel Rollout", muscleGroups: [.abs], equipment: .other, category: .isolation,
                 description: "Ab wheel rollout for deep core activation.",
                 tips: ["Start from knees", "Don't collapse at the bottom", "Brace core throughout"]),
        Exercise(id: "ex-cable-woodchop", name: "Cable Woodchop", muscleGroups: [.abs], equipment: .cable, category: .isolation,
                 description: "Rotational cable movement for obliques and core.",
                 tips: ["Rotate through your torso, not your arms", "Keep arms extended", "Control the return"]),
        Exercise(id: "ex-russian-twist", name: "Russian Twist", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Seated twist for oblique and core engagement.",
                 tips: ["Lean back slightly with feet off the ground", "Rotate through your torso", "Touch the ground on each side"]),
        Exercise(id: "ex-decline-situp", name: "Decline Sit-up", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Sit-up on a decline bench for increased ab resistance.",
                 tips: ["Hook feet under the pads", "Cross arms over chest or behind head", "Control the negative"]),
        Exercise(id: "ex-dead-bug", name: "Dead Bug", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Supine core stability exercise extending opposite arm and leg.",
                 tips: ["Keep lower back pressed into the floor", "Extend opposite arm and leg slowly", "Exhale as you extend"]),
        Exercise(id: "ex-pallof-press", name: "Pallof Press", muscleGroups: [.abs], equipment: .cable, category: .isolation,
                 description: "Anti-rotation cable press for deep core stability.",
                 tips: ["Stand sideways to the cable", "Press straight out from your chest", "Resist the rotation — that's the work"]),
        Exercise(id: "ex-mountain-climbers", name: "Mountain Climbers", muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Dynamic plank variation driving knees to chest for core and cardio.",
                 tips: ["Keep hips level — don't bounce them up", "Drive knees toward chest quickly", "Keep core braced throughout"]),
    ]
    
    // MARK: - Unilateral / New Exercises (added in workout-bugs-190)
    static let unilateral: [Exercise] = [
        // Chest
        Exercise(id: "ex-single-arm-cable-press", name: "Single-Arm Cable Chest Press",
                 muscleGroups: [.chest, .triceps], equipment: .cable, category: .compound,
                 description: "Standing cable press with one arm at a time for chest isolation and anti-rotation core work.",
                 tips: ["Set cable at chest height", "Keep your core braced against the rotation", "Press straight out, not across your body"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-floor-press", name: "Single-Arm Dumbbell Floor Press",
                 muscleGroups: [.chest, .triceps], equipment: .dumbbell, category: .compound,
                 description: "Floor press with one dumbbell, limiting ROM and emphasizing lockout strength.",
                 tips: ["Lie on the floor with one arm extended", "Lower elbow until it touches the floor", "Press explosively"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Back
        Exercise(id: "ex-single-arm-lat-pulldown", name: "Single-Arm Lat Pulldown",
                 muscleGroups: [.lats, .biceps], equipment: .cable, category: .compound,
                 description: "D-handle pulldown one side at a time for unilateral lat development.",
                 tips: ["Slight lean back", "Pull elbow to hip", "Full stretch at the top"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-cable-row", name: "Single-Arm Cable Row",
                 muscleGroups: [.back, .lats, .biceps], equipment: .cable, category: .compound,
                 description: "Seated or standing single-arm cable row with a D-handle.",
                 tips: ["Keep chest up", "Pull elbow back past torso", "Squeeze at peak contraction"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-db-pullover", name: "Dumbbell Pullover",
                 muscleGroups: [.lats, .chest], equipment: .dumbbell, category: .isolation,
                 description: "Lying pullover with a dumbbell for lat and chest stretch.",
                 tips: ["Slight bend in elbows throughout", "Lower the dumbbell behind your head until you feel a stretch", "Pull back over your chest with lats"]),
        Exercise(id: "ex-single-arm-machine-row", name: "Single-Arm Machine Row",
                 muscleGroups: [.back, .lats], equipment: .machine, category: .compound,
                 description: "Plate-loaded or selectorized row machine used one arm at a time.",
                 tips: ["Adjust chest pad so arm fully extends", "Pull to stomach level", "Squeeze shoulder blade at peak"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-meadows-row", name: "Meadows Row",
                 muscleGroups: [.back, .lats], equipment: .barbell, category: .compound,
                 description: "Single-arm landmine row named after John Meadows — great for upper back thickness.",
                 tips: ["Stagger your feet", "Pull the bar to your hip", "Lead with your elbow"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Shoulders
        Exercise(id: "ex-single-arm-db-shoulder-press", name: "Single-Arm Dumbbell Shoulder Press",
                 muscleGroups: [.shoulders, .triceps], equipment: .dumbbell, category: .compound,
                 description: "One-arm dumbbell shoulder press standing or seated.",
                 tips: ["Brace core for anti-rotation", "Press straight overhead", "Keep shoulder packed"],
                 supportedPositions: [.seated, .standing],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-landmine-press", name: "Single-Arm Landmine Press",
                 muscleGroups: [.chest, .shoulders], equipment: .barbell, category: .compound,
                 description: "Landmine press done strictly one arm at a time.",
                 tips: ["Press at an angle, not straight up", "Brace your core hard", "Full extension at the top"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-face-pull", name: "Cable Face Pull (Single-Arm)",
                 muscleGroups: [.shoulders, .traps], equipment: .cable, category: .isolation,
                 description: "D-handle face pull one arm at a time for rear delt and rotator cuff work.",
                 tips: ["Pull to face level", "Externally rotate at the end", "Control the weight back"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Biceps
        Exercise(id: "ex-single-arm-cable-curl", name: "Single-Arm Cable Curl",
                 muscleGroups: [.biceps], equipment: .cable, category: .isolation,
                 description: "D-handle cable curl one arm at a time for constant tension.",
                 tips: ["Keep elbow pinned to side", "Squeeze at the top", "Control the negative"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-machine-preacher", name: "Single-Arm Preacher Curl (Machine)",
                 muscleGroups: [.biceps], equipment: .machine, category: .isolation,
                 description: "Single-arm preacher machine curl for strict bicep isolation.",
                 tips: ["Full stretch at bottom", "Don't swing", "Slow on the way down"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-cross-body-hammer-curl", name: "Cross-Body Hammer Curl",
                 muscleGroups: [.biceps, .forearms], equipment: .dumbbell, category: .isolation,
                 description: "Alternating hammer curls across the body targeting the long head of the bicep.",
                 tips: ["Curl across your body to the opposite shoulder", "Neutral grip throughout", "Alternate arms each rep"],
                 supportsUnilateral: true, defaultLaterality: .alternating),
        Exercise(id: "ex-bayesian-curl", name: "Bayesian Curl",
                 muscleGroups: [.biceps], equipment: .cable, category: .isolation,
                 description: "Cable curl with arm extended behind the body for maximum long-head stretch.",
                 tips: ["Set cable low and stand with arm behind you", "Curl from full extension", "Don't let elbow drift forward"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Triceps
        Exercise(id: "ex-single-arm-pushdown", name: "Single-Arm Tricep Pushdown",
                 muscleGroups: [.triceps], equipment: .cable, category: .isolation,
                 description: "D-handle cable pushdown one arm at a time.",
                 tips: ["Pin elbow to side", "Full extension", "Squeeze at the bottom"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-cable-oh-ext", name: "Single-Arm Overhead Cable Extension",
                 muscleGroups: [.triceps], equipment: .cable, category: .isolation,
                 description: "One-arm overhead cable extension for long-head tricep stretch.",
                 tips: ["Set cable high, face away", "Keep elbow pointing at ceiling", "Full extension and squeeze"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Quads / Glutes
        Exercise(id: "ex-single-leg-press", name: "Single-Leg Leg Press",
                 muscleGroups: [.quads, .glutes], equipment: .machine, category: .compound,
                 description: "One leg on the sled for unilateral quad and glute development.",
                 tips: ["Same setup as bilateral — just use one leg", "Don't let knee cave in", "Full range of motion"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-leg-ext", name: "Single-Leg Extension",
                 muscleGroups: [.quads], equipment: .machine, category: .isolation,
                 description: "Leg extension machine used one leg at a time to correct imbalances.",
                 tips: ["Pause at full extension", "Control the negative", "Don't use momentum"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-pistol-squat", name: "Pistol Squat",
                 muscleGroups: [.quads, .glutes], equipment: .bodyweight, category: .compound,
                 description: "Full single-leg squat requiring balance, mobility, and strength.",
                 tips: ["Extend opposite leg forward", "Sit back and down on one leg", "Use a box or band for assistance if needed"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-reverse-lunge", name: "Reverse Lunge",
                 muscleGroups: [.quads, .glutes, .hamstrings], equipment: .dumbbell, category: .compound,
                 description: "Step backward into a lunge for controlled lower body work.",
                 tips: ["Step straight back, not to the side", "Back knee almost touches the floor", "Drive through front heel to stand"],
                 supportsUnilateral: true, defaultLaterality: .alternating),
        Exercise(id: "ex-lateral-lunge", name: "Lateral Lunge",
                 muscleGroups: [.quads, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Side-stepping lunge for quad and glute medius work.",
                 tips: ["Step wide to the side", "Sit back into the hip", "Keep opposite leg straight"],
                 supportsUnilateral: true, defaultLaterality: .alternating),
        Exercise(id: "ex-split-squat", name: "Split Squat",
                 muscleGroups: [.quads, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Static lunge position (non-Bulgarian) for stable single-leg work.",
                 tips: ["Stagger feet, rear foot flat on floor", "Drop back knee straight down", "Keep front shin fairly vertical"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-curtsy-lunge", name: "Curtsy Lunge",
                 muscleGroups: [.quads, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Cross-behind lunge targeting the glute medius.",
                 tips: ["Cross rear foot behind and to the outside", "Lower back knee toward floor", "Drive through front heel to stand"],
                 supportsUnilateral: true, defaultLaterality: .alternating),
        Exercise(id: "ex-single-leg-hip-thrust", name: "Single-Leg Hip Thrust",
                 muscleGroups: [.glutes, .hamstrings], equipment: .bodyweight, category: .compound,
                 description: "Hip thrust with one leg extended for unilateral glute activation.",
                 tips: ["Back on bench, one leg extended forward", "Drive through the heel of the working leg", "Squeeze glute hard at the top"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-cable-kickback", name: "Cable Kickback",
                 muscleGroups: [.glutes], equipment: .cable, category: .isolation,
                 description: "Ankle strap cable kickback for glute isolation.",
                 tips: ["Keep a slight bend in the working knee", "Drive heel back and up", "Squeeze glute at the top"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-cable-hip-abduction", name: "Cable Hip Abduction",
                 muscleGroups: [.glutes], equipment: .cable, category: .isolation,
                 description: "Standing cable abduction with ankle strap for glute medius.",
                 tips: ["Stand sideways to the cable", "Raise leg straight out to the side", "Control the return"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Hamstrings
        Exercise(id: "ex-single-leg-rdl", name: "Single-Leg RDL",
                 muscleGroups: [.hamstrings, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Standing single-leg Romanian deadlift for hamstring strength and balance.",
                 tips: ["Hinge at the hip while balancing on one leg", "Keep a slight bend in the standing knee", "Maintain a flat back throughout"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-leg-curl", name: "Single-Leg Curl",
                 muscleGroups: [.hamstrings], equipment: .machine, category: .isolation,
                 description: "Leg curl machine used one leg at a time.",
                 tips: ["Control the negative", "Full range of motion", "Don't use momentum"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-kb-single-leg-rdl", name: "Kettlebell Single-Leg RDL",
                 muscleGroups: [.hamstrings, .glutes], equipment: .kettlebell, category: .compound,
                 description: "Kettlebell variant of the single-leg RDL.",
                 tips: ["Hold kettlebell in the opposite hand of the standing leg", "Keep a flat back", "Feel the stretch in the hamstring"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Calves
        Exercise(id: "ex-single-leg-calf-raise", name: "Single-Leg Calf Raise",
                 muscleGroups: [.calves], equipment: .bodyweight, category: .isolation,
                 description: "Standing on one foot calf raise, bodyweight or holding a dumbbell.",
                 tips: ["Hold onto something for balance if needed", "Full stretch at the bottom", "Pause at the top"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Forearms
        Exercise(id: "ex-single-arm-wrist-curl", name: "Single-Arm Wrist Curl",
                 muscleGroups: [.forearms], equipment: .dumbbell, category: .isolation,
                 description: "One arm at a time wrist curl for focused forearm flexor work.",
                 tips: ["Rest forearm on thigh or bench", "Full range of motion at the wrist", "Control the weight"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-reverse-wrist-curl", name: "Single-Arm Reverse Wrist Curl",
                 muscleGroups: [.forearms], equipment: .dumbbell, category: .isolation,
                 description: "Overhand single-arm wrist curl for forearm extensor development.",
                 tips: ["Rest forearm on thigh or bench", "Use lighter weight than standard wrist curl", "Controlled movement throughout"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),

        // Core
        Exercise(id: "ex-single-arm-farmers-carry", name: "Single-Arm Farmer's Carry",
                 muscleGroups: [.abs, .forearms, .traps], equipment: .dumbbell, category: .compound,
                 description: "Suitcase carry holding weight on one side for oblique and grip work.",
                 tips: ["Hold the dumbbell at your side", "Stay tall, don't lean toward the weight", "Brace your core against the side pull"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-single-arm-pallof-press", name: "Single-Arm Pallof Press",
                 muscleGroups: [.abs], equipment: .cable, category: .isolation,
                 description: "One-arm anti-rotation cable press for deep core stability.",
                 tips: ["Stand sideways to the cable", "Press straight out from your chest", "Resist the rotation — that's the work"],
                 supportedAttachments: [.dHandle],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-side-plank", name: "Side Plank",
                 muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Lateral isometric core hold for obliques and hip stability.",
                 tips: ["Stack feet or stagger them for balance", "Keep hips lifted — don't sag", "Hold for time"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-copenhagen-plank", name: "Copenhagen Plank",
                 muscleGroups: [.abs], equipment: .bodyweight, category: .isolation,
                 description: "Side plank with top leg on a bench, targeting adductors and obliques.",
                 tips: ["Rest top ankle or knee on a bench", "Keep hips elevated", "Hold for time or do reps"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-suitcase-deadlift", name: "Suitcase Deadlift",
                 muscleGroups: [.abs, .hamstrings, .glutes], equipment: .dumbbell, category: .compound,
                 description: "Deadlift holding weight on one side only to challenge core anti-lateral-flexion.",
                 tips: ["Hold the dumbbell at your side like a suitcase", "Stand tall, resist leaning toward the weight", "Same mechanics as a regular deadlift"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
    ]

    // MARK: - Machine & Cable Extras (added in #261)
    static let machineAndCableExtras: [Exercise] = [
        // Smith machine variations
        Exercise(id: "ex-smith-bench-press", name: "Smith Machine Bench Press", muscleGroups: [.chest, .triceps, .shoulders], equipment: .machine, category: .compound,
                 description: "Flat bench press on the Smith machine — guided bar path lets you push closer to failure safely.",
                 tips: ["Set bench so bar lines up with mid-chest", "Unrack by twisting the hooks off", "Don't bounce the bar off your chest"]),
        Exercise(id: "ex-smith-incline-press", name: "Smith Machine Incline Press", muscleGroups: [.chest, .shoulders, .triceps], equipment: .machine, category: .compound,
                 description: "Incline bench press on the Smith machine for upper chest with a fixed bar path.",
                 tips: ["Set bench to 30-45 degrees", "Bar should line up over upper chest", "Drive feet into the floor for stability"]),
        Exercise(id: "ex-smith-shoulder-press", name: "Smith Machine Shoulder Press", muscleGroups: [.shoulders, .triceps], equipment: .machine, category: .compound,
                 description: "Seated overhead press on the Smith machine for controlled shoulder work.",
                 tips: ["Adjust seat so the bar starts at chin level", "Press to full lockout overhead", "Brace core to avoid arching"],
                 supportedPositions: [.seated, .standing]),
        Exercise(id: "ex-smith-row", name: "Smith Machine Bent-Over Row", muscleGroups: [.back, .lats], equipment: .machine, category: .compound,
                 description: "Bent-over row with the Smith machine for a stable bar path and heavier loading.",
                 tips: ["Hinge at the hips to roughly 45 degrees", "Pull the bar to your lower ribs", "Keep your back flat throughout"],
                 supportedGrips: [.overhand, .underhand]),

        // Hammer Strength / iso-lateral plate-loaded
        Exercise(id: "ex-iso-lateral-row", name: "Hammer Strength Iso-Lateral Row", muscleGroups: [.back, .lats, .biceps], equipment: .machine, category: .compound,
                 description: "Plate-loaded iso-lateral row that lets each side work independently for balanced back development.",
                 tips: ["Adjust chest pad so arms fully extend", "Pull elbows back and squeeze shoulder blades", "Can be done bilaterally or one arm at a time"],
                 supportsUnilateral: true),
        Exercise(id: "ex-iso-lateral-chest-press", name: "Hammer Strength Iso-Lateral Chest Press", muscleGroups: [.chest, .triceps, .shoulders], equipment: .machine, category: .compound,
                 description: "Plate-loaded iso-lateral chest press for independent left/right pressing.",
                 tips: ["Adjust seat so handles align with mid-chest", "Press without locking out elbows", "Squeeze chest at full extension"],
                 supportsUnilateral: true),

        // Belt squat
        Exercise(id: "ex-belt-squat", name: "Belt Squat", muscleGroups: [.quads, .glutes], equipment: .machine, category: .compound,
                 description: "Squat loaded with a belt around the hips — heavy leg work without spinal compression.",
                 tips: ["Stand on the platform with belt around your waist", "Keep torso upright throughout", "Sit back and down through full range of motion"]),

        // Cable variations
        Exercise(id: "ex-cable-crossover", name: "Cable Crossover", muscleGroups: [.chest], equipment: .cable, category: .isolation,
                 description: "Mid-height cable fly bringing handles together in front of the chest.",
                 tips: ["Set pulleys at chest height", "Slight forward lean", "Bring handles together and pause for a squeeze"],
                 supportedAttachments: [.dHandle]),
        Exercise(id: "ex-cable-pull-through", name: "Cable Pull-Through", muscleGroups: [.glutes, .hamstrings], equipment: .cable, category: .compound,
                 description: "Hip hinge facing away from a low cable for posterior chain work.",
                 tips: ["Set cable at the lowest pulley", "Hinge at the hips, don't squat", "Squeeze glutes hard at the top"],
                 supportedAttachments: [.rope]),
        Exercise(id: "ex-cable-upright-row", name: "Cable Upright Row", muscleGroups: [.shoulders, .traps], equipment: .cable, category: .compound,
                 description: "Upright row using a low cable for constant tension on shoulders and traps.",
                 tips: ["Use a wider grip to reduce shoulder impingement", "Pull to upper chest height", "Lead with elbows"],
                 supportedAttachments: [.straightBar, .rope]),
        Exercise(id: "ex-cable-shrug", name: "Cable Shrug", muscleGroups: [.traps], equipment: .cable, category: .isolation,
                 description: "Cable shrug for constant tension trap development.",
                 tips: ["Use a straight bar at the lowest pulley", "Shrug straight up", "Pause at the top for a count"],
                 supportedAttachments: [.straightBar]),

        // Free-weight extras
        Exercise(id: "ex-trap-bar-deadlift", name: "Trap Bar Deadlift", muscleGroups: [.quads, .glutes, .hamstrings, .back, .traps], equipment: .barbell, category: .compound,
                 description: "Deadlift performed with a hex/trap bar — easier on the lower back, more quad-dominant than conventional.",
                 tips: ["Stand inside the bar with feet shoulder width", "Grip handles at your sides", "Drive through the floor with neutral spine"]),
        Exercise(id: "ex-zercher-squat", name: "Zercher Squat", muscleGroups: [.quads, .glutes, .abs], equipment: .barbell, category: .compound,
                 description: "Squat with the bar held in the crooks of the elbows — brutal on the core and upper back.",
                 tips: ["Hold bar in crooks of elbows, hands together", "Keep elbows up and torso upright", "Use a pad or sleeve for elbow comfort"]),
        Exercise(id: "ex-good-morning", name: "Good Morning", muscleGroups: [.hamstrings, .glutes, .back], equipment: .barbell, category: .compound,
                 description: "Hip-hinge with bar on the back for hamstring and posterior chain strength.",
                 tips: ["Bar high on traps", "Soft knees, hinge at the hips", "Stop when torso is parallel to floor"]),
        Exercise(id: "ex-box-squat", name: "Box Squat", muscleGroups: [.quads, .glutes, .hamstrings], equipment: .barbell, category: .compound,
                 description: "Squat to a box for fixed depth and explosive concentric strength.",
                 tips: ["Sit back fully onto the box — don't crash down", "Pause briefly without losing tightness", "Drive up explosively"]),

        // Kettlebell extras
        Exercise(id: "ex-kb-swing", name: "Kettlebell Swing", muscleGroups: [.glutes, .hamstrings, .back], equipment: .kettlebell, category: .compound,
                 description: "Two-handed kettlebell swing — explosive hip hinge for posterior chain power.",
                 tips: ["Hinge at the hips, don't squat", "Snap hips through to drive the bell up", "Bell finishes at chest/eye height, not overhead"]),
        Exercise(id: "ex-kb-goblet-squat", name: "Kettlebell Goblet Squat", muscleGroups: [.quads, .glutes], equipment: .kettlebell, category: .compound,
                 description: "Goblet squat holding a kettlebell at chest height.",
                 tips: ["Hold kettlebell by the horns at chest", "Elbows inside knees at the bottom", "Keep torso upright"]),
    ]

    // MARK: - Bodyweight Extras (added in #261)
    static let bodyweightExtras: [Exercise] = [
        Exercise(id: "ex-pike-pushup", name: "Pike Pushup", muscleGroups: [.shoulders, .triceps], equipment: .bodyweight, category: .compound,
                 description: "Pushup with hips piked high to shift load to the shoulders — bodyweight overhead press progression.",
                 tips: ["Form an inverted V with your body", "Lower the top of your head toward the floor", "Elevate feet to increase difficulty"]),
        Exercise(id: "ex-diamond-pushup", name: "Diamond Pushup", muscleGroups: [.triceps, .chest], equipment: .bodyweight, category: .compound,
                 description: "Close-stance pushup with hands forming a diamond — tricep-focused bodyweight press.",
                 tips: ["Form a diamond with thumbs and index fingers", "Keep elbows close to your ribs", "Lower chest to your hands"]),
        Exercise(id: "ex-decline-pushup", name: "Decline Pushup", muscleGroups: [.chest, .shoulders, .triceps], equipment: .bodyweight, category: .compound,
                 description: "Pushup with feet elevated on a bench or box for upper chest emphasis.",
                 tips: ["Feet on bench, hands on floor", "Keep core braced", "Lower chest to the floor"]),
        Exercise(id: "ex-inverted-row", name: "Inverted Row", muscleGroups: [.back, .lats, .biceps], equipment: .bodyweight, category: .compound,
                 description: "Bodyweight horizontal row under a fixed bar — great pull-up progression and mid-back builder.",
                 tips: ["Set a bar at hip height", "Hang underneath with arms extended", "Pull chest to the bar, body in a straight line"]),
        Exercise(id: "ex-band-pullover", name: "Band Pullover", muscleGroups: [.lats, .chest], equipment: .bands, category: .isolation,
                 description: "Lat-focused pullover using a resistance band anchored overhead.",
                 tips: ["Anchor the band overhead and grab with both hands", "Keep arms nearly straight", "Pull the band down to your thighs with your lats"]),
        Exercise(id: "ex-glute-bridge", name: "Glute Bridge", muscleGroups: [.glutes, .hamstrings], equipment: .bodyweight, category: .compound,
                 description: "Bodyweight bridge driving hips up — foundational glute activation drill.",
                 tips: ["Lie on your back, knees bent, feet flat", "Drive hips up by squeezing glutes", "Pause at the top, don't hyperextend"]),
        Exercise(id: "ex-side-lying-hip-abduction", name: "Side-Lying Hip Abduction", muscleGroups: [.glutes], equipment: .bodyweight, category: .isolation,
                 description: "Lying on your side, raise the top leg straight up to target the glute medius.",
                 tips: ["Keep top leg straight and toes pointed slightly down", "Raise leg slowly with no swinging", "Squeeze the side glute at the top"],
                 supportsUnilateral: true, defaultLaterality: .unilateral),
        Exercise(id: "ex-nordic-curl", name: "Nordic Hamstring Curl", muscleGroups: [.hamstrings], equipment: .bodyweight, category: .isolation,
                 description: "Kneeling, lower yourself slowly with feet anchored — eccentric hamstring builder.",
                 tips: ["Anchor feet under a bench or pads", "Lower yourself slowly using only your hamstrings", "Catch with your hands and push back up"]),
        Exercise(id: "ex-reverse-hyper", name: "Reverse Hyperextension", muscleGroups: [.glutes, .hamstrings, .back], equipment: .bodyweight, category: .isolation,
                 description: "Hip extension on a bench or reverse hyper machine for glutes and lower back.",
                 tips: ["Hips hang off the bench, hold the front", "Squeeze glutes to lift legs to parallel", "Don't hyperextend the lower back"]),
        Exercise(id: "ex-glute-ham-raise", name: "Glute Ham Raise", muscleGroups: [.hamstrings, .glutes, .calves], equipment: .machine, category: .compound,
                 description: "GHR machine hamstring raise — knee flexion + hip extension for full hamstring development.",
                 tips: ["Set the pad just under your hips", "Lower under control with arms crossed", "Drive yourself back up using your hamstrings"]),
    ]

    // MARK: - Mobility / Stretching (added in #261)
    static let mobility: [Exercise] = [
        Exercise(id: "ex-worlds-greatest-stretch", name: "World's Greatest Stretch", muscleGroups: [.hamstrings, .glutes, .back, .shoulders], equipment: .bodyweight, category: .stretching,
                 description: "Multi-plane mobility flow combining a lunge, thoracic rotation, and hip opener.",
                 tips: ["Step into a deep lunge", "Drop opposite hand to the floor", "Rotate top arm up toward the ceiling, then alternate"]),
        Exercise(id: "ex-cat-cow", name: "Cat-Cow", muscleGroups: [.back, .abs], equipment: .bodyweight, category: .stretching,
                 description: "Spinal flexion and extension drill on hands and knees.",
                 tips: ["Start in a tabletop position", "Inhale: drop belly, lift chest and tailbone", "Exhale: round spine and tuck chin"]),
        Exercise(id: "ex-90-90-hip-stretch", name: "90/90 Hip Stretch", muscleGroups: [.glutes, .hamstrings], equipment: .bodyweight, category: .stretching,
                 description: "Seated hip mobility drill with both legs at 90-degree angles.",
                 tips: ["Front leg bent at 90 degrees, back leg also at 90", "Sit tall and lean forward over the front shin", "Switch sides for equal time"]),
    ]

    // MARK: - Search
    static func search(_ query: String) -> [Exercise] {
        if query.isEmpty { return all }
        let lowered = query.lowercased()
        return all.filter {
            $0.name.lowercased().contains(lowered) ||
            $0.muscleGroups.contains(where: { $0.rawValue.contains(lowered) }) ||
            $0.equipment.rawValue.contains(lowered)
        }
    }
    
    static func byMuscleGroup(_ group: MuscleGroup) -> [Exercise] {
        all.filter { $0.muscleGroups.contains(group) }
    }
    
    static func byEquipment(_ equipment: Equipment) -> [Exercise] {
        all.filter { $0.equipment == equipment }
    }
}
